In [1]:
import numpy as np
import pandas as pd
x = [[1,2],[3,4]]
np.concatenate([x,x],axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [2]:
np.concatenate([x,x],axis=0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [8]:
np.concatenate([[x],[x]],axis=0)


array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [9]:
ser1 = pd.Series(['A',"B",'C'],index=[1,2,3])
ser2 = pd.Series(['D','E','F'],index=[4,5,6])
pd.concat([ser1,ser2])


1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [10]:
def make_df(cols,ind):
    data = {c: [str(c)+str(i) for i in ind] for c in cols}
    return pd.DataFrame(data,ind)

In [11]:
make_df('ABC',range(3))



A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [12]:
df1 = make_df('AB',[1,2])
df2 = make_df('AB',[3,4])
print(df1);print(df2);print(pd.concat([df1,df2]))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [13]:
df3 = make_df('AB',[0,1])
df4 = make_df('CD',[0,1])
print(df3);print(df4);print(pd.concat([df3,df4],axis=1))

    A   B
0  A0  B0
1  A1  B1
    C   D
0  C0  D0
1  C1  D1
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1


In [17]:
pd.concat([df3,df4],axis=0,sort=False)

A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1

In [18]:
np.concatenate([df3,df4],axis=1)

array([['A0', 'B0', 'C0', 'D0'],
       ['A1', 'B1', 'C1', 'D1']], dtype=object)

In [23]:
np.concatenate([df3,df4],axis=0)[0:2,0:1]

array([['A0'],
       ['A1']], dtype=object)

### 类似join的合并
·  join='inner'对所有输入列进行交集合并
·  join='outer'对所有输入列进行并集合并

In [27]:
df5 = make_df('ABC',[1,2])
df6 = make_df('BCD',[3,4])
print(df5);print(df6);print(pd.concat([df5,df6],sort=False))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


In [28]:
print(pd.concat([df5,df6],join='inner'))
print(pd.concat([df5,df6],join='outer',sort=False))

    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


### 设置join_axes参数，里面是索引对象构成列表（是列表的列表）

In [29]:
pd.concat([df5,df6],join_axes=[df5.columns])

A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4