In [2]:
import pandas as pd

pd.MultiIndex.from_arrays([['a','a','b','b'],
                           [1,2,1,2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

### 多级列索引

In [6]:
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],
                                   names=['years','visit'])
columns = pd.MultiIndex.from_product([['Bob','Guido','Sue'],['HR','Temp']],
                                     names=['subject','type'])

In [7]:
import numpy as np
data = np.round(np.random.randn(4,6),1)
data

array([[-1.2,  0.3,  1.3,  0.3, -0.6,  1.1],
       [ 2.9,  0.6, -0.8,  0.7,  0.5,  0.4],
       [-1. ,  2. , -1.4,  0.8,  0.6,  0.5],
       [ 2.1,  0.6, -1. , -0.7,  0.1,  0.1]])

In [8]:
data[:,::2]*=10
data

array([[-12. ,   0.3,  13. ,   0.3,  -6. ,   1.1],
       [ 29. ,   0.6,  -8. ,   0.7,   5. ,   0.4],
       [-10. ,   2. , -14. ,   0.8,   6. ,   0.5],
       [ 21. ,   0.6, -10. ,  -0.7,   1. ,   0.1]])

In [9]:
data += 37
data

array([[25. , 37.3, 50. , 37.3, 31. , 38.1],
       [66. , 37.6, 29. , 37.7, 42. , 37.4],
       [27. , 39. , 23. , 37.8, 43. , 37.5],
       [58. , 37.6, 27. , 36.3, 38. , 37.1]])

In [10]:
health_data = pd.DataFrame(data,index=index,columns=columns)
health_data


subject       Bob       Guido         Sue      
type           HR  Temp    HR  Temp    HR  Temp
years visit                                    
2013  1      25.0  37.3  50.0  37.3  31.0  38.1
      2      66.0  37.6  29.0  37.7  42.0  37.4
2014  1      27.0  39.0  23.0  37.8  43.0  37.5
      2      58.0  37.6  27.0  36.3  38.0  37.1

In [11]:
health_data['Guido']

type           HR  Temp
years visit            
2013  1      50.0  37.3
      2      29.0  37.7
2014  1      23.0  37.8
      2      27.0  36.3

In [13]:
data_mean = health_data.mean(level="years")
data_mean

subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
years                                         
2013     45.5  37.45  39.5  37.50  36.5  37.75
2014     42.5  38.30  25.0  37.05  40.5  37.30

In [14]:
data_mean.mean(axis=1,level='type')

type     HR       Temp
years                 
2013   40.5  37.566667
2014   36.0  37.550000